version: '3'

services:
  frontend:
    image: node:14
    container_name: mogutou-frontend
    working_dir: /app
    volumes:
      - ./web:/app
    ports:
      - "9528:9528"
    command: sh -c "npm install && npm run dev"
    environment:
      - HOST=0.0.0.0
      - PORT=9528
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile.custom
    container_name: mogutou-backend
    ports:
      - "1988:1988"
    volumes:
      - ./conf:/etc/conf
    environment:
      - MOGUTOU_DB=mysql
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    container_name: mogutou-mysql
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=ircnjfdhnvxwz.
      - MYSQL_DATABASE=mgt
